### ISSUE TITLE
Define the use of GitHub Teams as FINOS project team mechanism within ODP

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#10]
### Description of Problem:
The Open Developer Platform needs to provide consolidated documentation and guidance on the use of GitHub Teams so FINOS projects know how to form PMC and contributor relationships.

The feature is already in use for some FINOS projects/repositories, but there is no consolidation, nor public documentation that shows the "FINOS way" to map permissions within hosted repositories.

### Potential Solutions:
- [ ] Arrange a date when the GitHub team can join an ODP working group call 
- [ ] Place the GitHub Teams grooming session on the ODP agenda
- [ ] Review [FINOS on GitHub - settings and processes.pdf](https://github.com/finos/open-developer-platform/files/4072822/FINOS.on.GitHub.-.settings.and.processes.pdf) created by @maoo and @jbjonesjr
- [ ] Discuss the top 3 items ODP needs to deliver to move GitHub Teams forward
- [ ] Add the top 3 items to the ODP GitHub issues and delegate to ODP team members to solve
- [ ] Add items updates to future agenda to help unblock and move forward

**Comment by maoo** [comment]
Closing this one, as I created a more comprehensive item on https://github.com/finos/open-developer-platform/issues/71
