### ISSUE TITLE
Checking project activation criteria for ODP Project

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#102]
Based on https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530376/Activation , the following items need to be provided in order to request project activation for ODP.

I've added notes close to each item

# QUALITY & SECURITY
- [ ] **Development Process** - Repo Permissions are configured according to FINOS guidance. CI/CD is applied (where possible). TODO - manage and document versioning
Build & Release	- TODO - create 0.9 tag and release in GitHub . Add docs in README re. versions
- [ ] **Security** - ODP uses WhiteSource integration to run continuous scanning. TODO - No OWASP Top 10 warnings are present in the code (maybe use [barista](https://github.com/Optum/barista)?)
- [x] **Documentation** - Check https://github.com/finos/open-developer-platform/ and http://odp.finos.org/docs/what-is-odp

# DIVERSITY & VIABILITY
- [ ] **Community** - Vendors, project leads and DevOps specialists are the profiles that compose the ODP team; although alternating, vendors (like WhiteSource, RedHat and Fossa) keep a constant presence. Several FINOS projects rely on ODP collaboration tools (ie meeting attendance tracking, website automated publishing, artifact release automation, etc). TODO - validate this with PMC - would be great to ask for a testimonial from FDC3, Plexus, Alloy and Perspective projects, that can be published on odp.finos.org
- [ ] **Project Team** - ODP works closely with the OSR initiative to advance the FinServ Delivery acceleration. TODO - validate this with PMC
- [x] **License** - ODP does not ship any runtime binary; outbound licenses are documented on github.com/finos/open-developer-platform
- [x] **Trademark** - Trademark is enforced in odp.finos.org and github.com/finos/open-developer-platform
- [x] **Progress** - Roadmap is available on odp.finos.org/docs/roadmap and can be tracked on https://github.com/finos/open-developer-platform/milestones
- [ ] **Versioning** - TODO Release 0.9 (cleanup actions code first)
- [ ] **FINOS Support** - The ODP Team have always managed and executed on their backlog independently - TODO - validate this with PMC

# GROWTH & ADOPTION
- [ ] **Usefulness** - TODO - similar to the `Community` item above
- [x] **Status Badging** - Check badge in README.md , currently stating INCUBATING
- [ ] **Compliance** - TODO - enforce license in file headers
- [x] **Transparency** - Done, read more on http://odp.finos.org/docs/team

**Comment by maoo** [comment]
A new issue have been created to walk through the checklists, see https://github.com/finos/open-developer-platform/issues/107 .

Closing this as dup, but some content here may still be useful.
