### ISSUE TITLE
Rollout new GitHub automated features  to Cloud Service Certification, KDB, FDC3 and other important FINOS projects

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#104]
This item is related to the following Agenda and Minutes example as created and demonstrated within the Open Developer Platform. 
- https://github.com/finos/open-developer-platform/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting

### Tasks:
- [ ] present to Cloud Service Certification
- [ ] present to Security Reference Architecture
- [ ] present to FDC3
- [ ] present to Plexus

**Comment by mcleo-d** [comment]
The **Cloud Service Certification** project was [briefed on the initiative on March 26th](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1487306766/2020-03-26+Cloud+Service+Certification+Project+Meeting) and have agreed to adopt the functionality moving into the next meeting on April 9th from 10am – 11am ET 🚀

**Comment by mcleo-d** [comment]
Announce email being created by @mcleo-d and @maoo in the following restricted Google Doc ...
* https://docs.google.com/document/d/1QRzcDFKRXesFTeLZ6hUUGSKlUI8ff-SnRQv9lwCKCHQ/edit?usp=sharing

**Comment by maoo** [comment]
Closing this issue, as it seems we delivered everything. @mcleo-d - can you please review and reopen, in case something is missing?
