### ISSUE TITLE
WhiteSource integration across remaining FINOS projects

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#108]
### Description

Following the work done in #35 and the FINOS announcement on March 9th 2020 the following FINOS projects require WhiteSource integration to be completed.

- [ ] finos-plexus.github.io
- [ ] perspective
- [ ] cloud-service-certification
- [ ] kdb
- [ ] greenkey-discovery-sdk
- [ ] greenkey-asrtoolkit

### WhiteSource Documentation and FINOS Integration Support

Documentation related to WhiteSource integration and FINOS support is found on the FINOS wiki below.

- https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530440/WhiteSource

**Comment by maoo** [comment]
we're tracking progress internally for the security rollout. closing this issue
