### ISSUE TITLE
Process and automation for FINOS team to know about all project releases

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#109]
## Feature Request

- [ ] Create script notifies and reports new project releases

**Comment by maoo** [comment]
I think libraries.io could be the answer here, check https://libraries.io/api#repository-projects

I tested it with Perspective and it works, using `https://libraries.io/api/github/finos/perspective/projects?api_key=xxx`. We may want to also check on:
- [ ] RestApiClient (NuGet)
- [ ] FINOS Parent POM (Maven)
- [ ] preferably also something in Python

The API call would be quite simple to integrate in metadata-tool (no more than 1 day work)

**Comment by mindthegab** [comment]
Requirement for this would for marketing@ (/cc @toshaellison should define how) to have visibility on all releases so we can in the most automated way notify the community (via newsletter, announce, Twitter, whatever we decide).

Also I think we will have to integrate something like that in the project reports so that projects that don’t have releases for a while get flagged.

So before any work here, I think @toshaellison and @grizzwolf should define marketing requirements and together with @brooklynrob @mcleo-d we need to the work to define consolidated project reports.

I think target for this would be the June newsletter to have it done.

As a more general comment:

This was not prioritized on Monday. So not sure why we’re spending time on this when I see still 4 issues opened in prioritized. Kanban doesn’t work with too many in progress issues and also if this issue is being worked on should be in progress. Plus candidly we all have so many things on our plate that asking to provide input at this time can be distracting for everyone.

**Comment by mindthegab** [comment]
Note it should also track other means of publishing releases, eg Github hosted releases.

**Comment by maoo** [comment]
Adding LFX label, we should have a way to track releases in LF Insights.
