### ISSUE TITLE
Add GitHub Actions as build system within ODP infrastructure

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#11]
### Description of Problem:
The Open Developer Platform needs to form an opinion on the use of GitHub Actions so FINOS projects know how to configure their CI/CD pipelines using the most appropriate mechanisms

### Potential Solutions:
- [ ] Arrange a date when the GitHub team can join an ODP working group call 
- [ ] Place the GitHub Actions grooming session on the ODP agenda
- [ ] Discuss the top 3 items ODP needs to investigate, solve and deliver to move GitHub Actions forward
- [ ] Add the top 3 items to the ODP GitHub issues and delegate to ODP team members to solve
- [ ] Add items updates to future agenda to help unblock and move forward

**Comment by mcleo-d** [comment]
Potentially related to #18

**Comment by maoo** [comment]
Done! See https://odp.finos.org/docs/development-infrastructure/continuous-integration/intro/#github-actions
