### ISSUE TITLE
Announce and socialise automated GitHub actions for governance, quality and compliance checks

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#114]
## Goals
- Announce FINOS automated project compliance scan - https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530344/Code+Validation#CodeValidation-Projectcompliancescan - also check the [project-blueprint documentation](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-Built-inprojectwebsite), which contains all repo contents and settings
-  Announce meeting minutes - https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-MeetingMinutes
-  Announce automated invitation to FINOS GitHub org - https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-BecomingGitHubFINOSOrganizationmember
- Run checks and monitor execution

## Tasks
- [x] Draft email to community@finos.org and schedule sending
- [x] Review email internally
- [x] Send email - _Monday 4th May_
- [x] Confirm that the action is creating GitHub issues and sending invitations as expected
- [x] @mcleo-d and @toshaellison to understand the right platform for introducing directly to FINOS project leads once background email has been sent.
- [x] Add `invite-clas-to-finos-org` to the a schedule GitHub Action (as done for [project compliance&quality](https://github.com/finos/open-developer-platform/blob/master/.github/workflows/project-compliance-quality.yml))

## Related to:
- Ensure all GitHub repositories comply with project-blueprint repo template #31
- Automatically invite people to github.com/orgs/finos/people when CLA covered https://github.com/finos/metadata-tool/issues/54
- Implement meeting minutes (and attendance tracking) on GitHub #78

This item was moved to #139 

- Enable [project quality&compliance check](https://github.com/finos/open-developer-platform/blob/master/scripts/generate-repo-issues.sh#L17) and [automated invitation](https://github.com/finos/metadata-tool/blob/master/src/metadata_tool/sources/github.clj#L125) actions

**Comment by mcleo-d** [comment]
Related to https://github.com/finos/metadata-tool/issues/54

**Comment by mcleo-d** [comment]
Announce email being created by @mcleo-d and @maoo in the following restricted Google Doc ...
* https://docs.google.com/document/d/1QRzcDFKRXesFTeLZ6hUUGSKlUI8ff-SnRQv9lwCKCHQ/edit?usp=sharing

**Comment by mcleo-d** [comment]
@maoo - Draft email done and available 👇 for review and feedback ...  

* [https://docs.google.com/document/d/1QRzcDFKRXesFTeLZ6hUUGSKlUI8ff-SnRQv9lwCKCHQ/edit?usp=sharing](https://docs.google.com/document/d/1QRzcDFKRXesFTeLZ6hUUGSKlUI8ff-SnRQv9lwCKCHQ/edit?usp=sharing) 👀

Enjoy! 😁 

James.

**Comment by mcleo-d** [comment]
@brooklynrob and @toshaellison suggests ... 

@mcleo-d to add to the agenda of PMC meetings to introduce directly to the community once background email has been sent.

James.

**Comment by maoo** [comment]
Decided to go out this Thursday 30th

**Comment by mcleo-d** [comment]
It was agreed to email each team to update them on enabling the ODP items and meet the teams in project meetings moving forward. 

The following table highlights the teams that have been contacted and our ability to move forward. 

| Team        | Update           | Proceed  |
| ------------- | ------------- |:-----:|
| Perspective | Emailed Neil and Rhyddian. Awaiting feedback from team before enabling features. | No |
| DataHelix      | The team have been contacted and ready to join project meeting | <ul><li>[ ] _proceed_</li></ul> |
| Synthetic DataHub | The team have been contacted and ready to join project meeting | <ul><li>[ ] _proceed_</li></ul> |
| Waltz | The team have been contacted and ready to join project meeting | <ul><li>[ ] _proceed_</li></ul> |
| CLA Bot | The team have been contacted and ready to join project meeting | <ul><li>[ ] _proceed_</li></ul> |
| OpenFin React Hooks | The team have been contacted and ready to join project meeting | <ul><li>[ ] _proceed_</li></ul> |
| Plexus Interop | The team have been contacted and ready to join project meeting | <ul><li>[ ] _proceed_</li></ul> |
| Plexus Desktop Interop API | The team have been contacted and ready to join project meeting | <ul><li>[ ] _proceed_</li></ul> |

**Comment by mcleo-d** [comment]
@maoo - This is to confirm the GitHub actions for governance, quality and compliance checks were socialised during the FINOS All Community call on Thursday 11th June. This means the socialisation task is now complete.

**Comment by maoo** [comment]
All done! Re. quality reports, check issue #139
