### ISSUE TITLE
GitHub Action to run OWASP Dependency-Check

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#119]
## Feature Request

Create a GitHub Action (as independent GitHub repository, following GitHub Actions development best practices) that scans a repository using the [OWASP Dependency-Check](https://github.com/jeremylong/DependencyCheck)

## Tasks
- [ ] Develop Action
- [ ] Test Action
- [ ] Document Action on ODP Wiki page
- [ ] Enable Action on FINOS projects
- [ ] Add Action to project-blueprint
- [ ] Announce and socialise

**Comment by MarcoEidinger** [comment]
Are you aware of https://github.com/Sburris/dependency-check-action ? This might fit your needs or can act as a starting point..

**Comment by maoo** [comment]
@MarcoEidinger , yes, definitely! Would be good to see it in action, maybe on this repository?

If you or anyone else would like to submit a PR to this repo, so that we can play a bit around it and build some docs to host on odp.finos.org (or even add it to the [FINOS project blueprint](github.com/finos/project-blueprint)!), that would be awesome.

**Comment by maoo** [comment]
We've delivered github actions around the OWASP DC plugin, checkout https://github.com/maoo/security-scanning

Closing this issue, we can create new items in repo mentioned above.
