### ISSUE TITLE
Create a FINOS wiki pattern on GitHub for FINOS projects to follow as best working practice

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#12]
### Description of Problem:
The Open Developer Platform needs to create a pattern for engaging FINOS wikis on GitHub so FINOS projects can follow the pattern as a best working practice.

### Stories:
- [x] Arrange a date when the GitHub team can join an ODP working group call 
- [x] Place the GitHub wiki discussion and initial grooming session on the ODP agenda
- [x] Discuss the initial items ODP needs to investigate, solve and deliver to move GitHub hosted wikis forward
- [x] Add the initial items to the ODP GitHub issues and delegate to ODP team members to solve
- [x] Add wiki updates to future ODP agenda to help unblock and move forward
- [x] Create blueprint microsite using ODP white label Docusaurus template on the following ODP branch : https://github.com/finos/open-developer-platform/tree/odp-issues-37-docusaurus-white-label-wiki  
- [x] #19 Create a GitHub action to publish white labeled ODP Docusaurus content
- [x] #37 Create an ODP microsite and wiki using the Docusaurus JavaScript framework

**Comment by maoo** [comment]
@mcleo-d  - just added an important requirement in the list above: tracking meeting attendance on GitHub MarkDown files (plus, managing the meeting agenda lifecycle in GitHub). That's a crucial part of our day-by-day at FINOS, and Docusaurus + MarkDown could provide a nice setup.

Didn't decompose the issues as there may be already some issues in JIRA pending migration that talk about this.

**Comment by mcleo-d** [comment]
@maoo and @grizzwolf - Have just raised the following PR against the FINOS Project Blueprint to merge the first build of a white label Docusaurus template for FINOS projects to use as a wiki reference architecture - https://github.com/finos/project-blueprint/pull/8

Once accepted we can move forward with #55 👍

**Comment by maoo** [comment]
Taking out the following items and resolving the issue. We will estimate each separate item before moving forward.

- [ ] #55 Add an "About FINOS" page to the project blueprint microsite that's inherited across all FINOS projects when new project microsites are created
- [ ] #39 Enhance metadata-tool to track meeting attendance on GitHub (Docusaurus MarkDown format)
- [ ] Test and document meeting agenda and attendance using Docusaurus (and MarkDown files on GitHub)
- [ ] #20 Create inline edit links as part of white labeled Docusaurus build
