### ISSUE TITLE
Improve docs around finos-team and finos-admins permissions

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#122]
**Tasks**
- [ ] Add finos-admins and finos-team in the access permission matrix
- [ ] Configure project-blueprint accordingly
- [ ] Try using  project-blueprint as template and check repo permissions
- [ ] Mention process on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-FINOSProjectblueprint according to findings

See https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-AccessControl (and related page on odp.finos.org)

**Comment by maoo** [comment]
Docs are now available on https://odp.finos.org/docs/project-collaboration
