### ISSUE TITLE
Enable automatic invite to GitHub FINOS org

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#136]
metadata-tool now provides the ability to send out an invitation to join the github.com/finos org, for all github users that are covered by FINOS CLA. It has been tested with a test user, and the final list of users pending invitation have been generated (See below).

Running the `lein run -- invite-clas-to-finos-org -m ../metadata` command, this is what we get:

```
Pending invitation:  1
FINOS members:  74
CLA covered people:  426
Members with no CLA:  #{... ...}
To invite:  353
```

Few interesting notes:
- Invitations expire after 1 week, so if somebody doesn't want (or can't join), and the invitation expires, by running again this comment, we would re-invite again all users who decided to ignore the first invitation. Since GitHub doesn't provide API to retrieve expired invitations, there's no (simple) way we can avoid this to happen
- There may be users in our metadata with outdated affiliations (ie they left the company but didnt notify us). I still believe it's safe to add them in our directory, considering they're corner cases. However, we need to check periodically that there are no GitHub members that are not covered by CLA (anymore).

### Tasks

- [x] @mcleo-d - To check list of users before we run the bulk invitation.
- [x] @mcleo-d - Create a filtered view of contributors the invitation should be sent to - https://github.com/finos/open-developer-platform/issues/136#issuecomment-641229962
- [x] @mcleo-d - Create an initial email to send to contributors outlining to expect a GitHub notification to join FINOS Teams - https://github.com/finos/open-developer-platform/issues/136#issuecomment-641229962
- [x] @mcleo-d - To send bcc'd email to all contributors to be invited to FINOS Teams https://github.com/finos/open-developer-platform/issues/136#issuecomment-641229962
- [x] @maoo - Send GitHub notifications to contributors using the following spreadsheet with `filter = Yes` in the `Invite Yes/No` column.
  - https://docs.google.com/spreadsheets/d/1uch-8rPEUwE8dnRkaox-XAdh6zQxG-ObTWWok2X6U5E/edit?usp=sharing
- [ ] Add all [failed invitations](https://github.com/orgs/finos/people/failed_invitations) to `:skip-invites` configuration
- [ ] Enable autoinvitation via GitHub Action (cron schedule)

/CC @toshaellison

**Comment by maoo** [comment]
As discussed last week, we want to send out a heads-up via email to those who would receive the invitation. I've emailed the info to @toshaellison and @mcleo-d , so they can move forward with the communication.

Please notify me when this happens, so I can plan ahead the bulk invitation.

Finally, I propose to skip enabling any automated invitation for now, rather than using this tool as bulk invitation mechanism, if and when we want to use it, which already gives us power to keep things in sync and inform community ahead of time.

We can always enable automation in the future.

**Comment by mcleo-d** [comment]
Hi @maoo 

Thanks for supplying the email addresses to me and @toshaellison. I have reviewed the list provided and have qualified the contributors in this [Initial FINOS Organisation Team Invite](https://docs.google.com/spreadsheets/d/1uch-8rPEUwE8dnRkaox-XAdh6zQxG-ObTWWok2X6U5E/edit?usp=sharing) Google Sheet.

Within the sheet I have created **CCLA/ICLA**, **Invite Yes/No** and **Notes** columns that tell you whether the person should be invited to the FINOS Organisation Team.

I have made a note in the **Notes** column where a person should not be invited to join and the reasons why. I am now moving onto the email content.

Cheers 🍻 

James.

**Comment by mcleo-d** [comment]
@maoo and @toshaellison,

I have created the following Google Doc that contains the first draft of the email to be sent to FINOS contributors being invited to join FINOS Teams in GitHub.

* https://docs.google.com/document/d/10crMpnssjruOoG0q8BLIybja4Yzab8Nyf_ojkEu8nbM/edit?usp=sharing

Please review and comment in the doc.

James.

**Comment by mcleo-d** [comment]
Hi @maoo - I can confirm emails have been sent to the people in the spreadsheet below to inform them to expect a GitHub notification inviting them to join Teams in the FINOS organisation.

Please filter `Yes` in the `Invite Yes/No` column.

* https://docs.google.com/spreadsheets/d/1uch-8rPEUwE8dnRkaox-XAdh6zQxG-ObTWWok2X6U5E/edit?usp=sharing

The content of email is outlined in the following Google doc.

* https://docs.google.com/document/d/10crMpnssjruOoG0q8BLIybja4Yzab8Nyf_ojkEu8nbM/edit?usp=sharing

**Comment by maoo** [comment]
Thanks @mcleo-d ! Given that the list is 348 items, whereas the original list was 353, it means that:
- 5 users haven't been invited; could you please tell me which ones you skipped? this way we can blacklist them into metadata and enable automatic invitation for the others
- 20 email addresses are unreacheable, and we can add a flag in metadata to keep track of these cases (and skip invitations)

WDYT?

**Comment by mcleo-d** [comment]
I think it'll be good to review the list over a shared screen before we move forward. Let me know when you're free for a chat? 😁

**Comment by maoo** [comment]
The list of emails have been stored into https://github.com/finos/metadata/blob/dev/gh-org-invite-bl.edn (internal) and implemented into metadata-tool . I've manually checked the output and users are correctly taken out, below a report:

```
Skip invitations: 42
Pending invitation: 5
FINOS members: 85
CLA covered people: 442
Members with no CLA - 4
To invite: 314
```

@mcleo-d - I'm ready to enable the feature and run it and enable the continuous run. I'll wait for your final ack.

**Comment by mcleo-d** [comment]
@maoo - I suggest scheduling the first invite notifications to be sent on Monday 15th June, as we want them to be received at the beginning of the working week, plus this avoids not needing to support over the weekend.

**Comment by mcleo-d** [comment]
Invites sent and issue closed. 

Review to happen between @mcleo-d and @maoo on 23rd June 2020 to review accepted and pending invitations.

**Comment by maoo** [comment]
Latest update on this....

<img width="308" alt="Screenshot 2020-06-22 at 16 15 16" src="https://user-images.githubusercontent.com/327285/85297895-a6d70600-b4a3-11ea-9eae-53f3fc83cb9d.png">

**Comment by maoo** [comment]
TODO
- [ ] Create issue to manually send out 3 invites, at specific dates/times
- [ ] Reach out to every GH FINOS member to switch the flag to public (GitHub discussions? Community email reach out?)

**Comment by maoo** [comment]
Latest update:

<img width="302" alt="Screenshot 2020-06-29 at 17 44 12" src="https://user-images.githubusercontent.com/327285/86026791-2a5a9f00-ba30-11ea-9bf2-2848711c1d51.png">

**Comment by maoo** [comment]
We decided not to enable any automatic invite automation.

Instead, we have implemented a command on metadata-tool that lists the GitHub usernames of all our project leads: `lein run -- list-project-leads -m ../metadata`.

Closing issue.
