### ISSUE TITLE
Pilot using "GitHub Teams", "GitHub Issues" or another GitHub mechanism to keep team conversations close to repositories and documentation

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#14]
### Description of Problem:
The ODP team should work with related FINOS project teams to trial, prove and answer the following questions, plus any other questions that are raised as part of the trial.

- What are the critical requirements of open source discussion forums from a FINOS team and bank perspective?
- Do "GitHub Teams" and "GitHub Issues" provide sufficient discussion monitoring, data collection, and auditing, required by the banks?
- Are there alternative places within the context of GitHub that better suit this requirement, other than Teams and Issues?
- Are there any benefits or hypothesis that should be measured and presented as part of the trial to demonstrate success criteria?

## Next Steps
- [ ] Prioritise the discussion forum trial against the ODP backlog
- [ ] Work with ODP team to understand trial success criteria and measures.
- [ ] Select relevant FINOS projects to help fulfil the trial
- [ ] Schedule the trial and write a new story / epic to accommodate on the ODP backlog

**Comment by mcleo-d** [comment]
Issues closed due to duplication
