### ISSUE TITLE
Archive content and redirect decentralized.finos.org microsite to finos.org

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#146]
## Request

This request removes the content of https://decentralized.finos.org and redirects to https://finos.org.

## Tasks

- [x] Archive content of https://decentralized.finos.org/ to a repository where it can be referred to in the future if needed
- [x] Remove microsite from all URLS where it's being hosted so not indexed by Google or inbound links
- [x] Redirect `https://decentralized.finos.org/` to `https://finos.org`

**Comment by toshaellison** [comment]
We might also consider redirecting to https://wiki.hyperledger.org/display/CMSIG/ (the Hyperledger Capital Markets SIG).

**Comment by mcleo-d** [comment]
I can confirm the redirect is now taking backlinks to https://www.finos.org as expected. 

See redirected screenshot below.

![Screenshot 2020-07-20 at 16 35 34](https://user-images.githubusercontent.com/6029572/87956649-340f7980-caa7-11ea-8a7a-0aefdf08961c.png)
