### ISSUE TITLE
Build website for the Open Source Readiness project

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#190]
The Open Source Readiness project is seeking help to build a website, to be hosted on `osr.finos.org`, that would host the following content:
- General information about the project: goals, mission, milestones, releases, team composition, meetings and more
- HTML version of the [OSLC handbook](https://github.com/finos/OSLC-handbook)
- HTML version of the [OSR checklist](https://github.com/finos/osr-checklists)
- Links and references to other FINOS initiatives, such as ODP and DevOps Mutualization

The layout should comply with the general FINOS styling guidelines, implemented by the [FINOS project blueprint](https://odp.finos.org/docs/project-collaboration/#finos-project-blueprint).

@copiesofcopies - could you please provide the following content below? Use [odp.finos.org](odp.finos.org) as reference.
- [ ] Define website menus and links
- [ ] Define homepage contents (title, subtitle, intro text, 3/4 "feature" blocks)

Let me know if you have any specific requirement, happy to adjust the aim.

## Tasks / definition of done
- [ ] Create the github.com/finos/open-source-readiness repo, using [FINOS project blueprint](https://odp.finos.org/docs/project-collaboration/#finos-project-blueprint)
- [ ] Implement GitHub Action to publish [OSLC handbook](https://github.com/finos/OSLC-handbook)
- [ ] Implement GitHub Action to publish [OSR checklist](https://github.com/finos/osr-checklists)
- [ ] Update configuration and contents on Docusaurus

**Comment by maoo** [comment]
Done! https://osr.finos.org/
