### ISSUE TITLE
Enable GitHub meeting attendance tracking for DevOps Mutualization

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#200]
## Feature Request
The DevOps Mutualization Special Interest Group uses GitHub Issues for their agenda and minutes tracking and requires the ODP `meeting-minutes-action` to be applied to the SIG repository below.

- [x] Apply `meeting-minutes-action` to the https://github.com/finos/devops-mutualization repository 
  - See https://github.com/finos/open-developer-platform/issues/200#issuecomment-749676693 by @mcleo-d 

This issue is also being tracked in the following DevOps Mutualization onboarding issue - https://github.com/finos/community/issues/77

- [x] Please comment on the DevOps Mutualization onboarding issue (https://github.com/finos/community/issues/77) once the functionality has been applied

Thank you.

**Comment by mcleo-d** [comment]
@maoo - I have raised PR https://github.com/finos/devops-mutualization/pull/15 to add `meeting-minutes-action` to DevOps Mutualization. The following tasks still need to be completed... 

- Add the following secrets defined in https://github.com/finos/devops-mutualization/settings/secrets
  - [ ] FINOS_TOKEN
  - [ ] GIT_CSV_TOKEN

**Comment by maoo** [comment]
All done @mcleo-d , secrets are added and PR is approved!

**Comment by mcleo-d** [comment]
Fantastic. Thank you @maoo 👍
