### ISSUE TITLE
Create a GitHub Issues, Teams and Discussion best practice for FINOS projects to follow

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#21]
### Description of Problem:
The Open Developer Platform needs to create a best practice for FINOS teams to engage through GitHub Issues, Teams and Discussions so FINOS projects can follow and replicate.

### Stories:
- [x] Arrange a date when the GitHub team can join an ODP working group call 
- [x] Place the GitHub discussion and initial grooming session on the ODP agenda
- [x] Discuss the initial items ODP needs to investigate, solve and deliver to move GitHub forward
- [x] Add the initial items to the ODP GitHub issues and delegate to ODP team members to solve
- [ ] Add updates to future ODP agenda to help unblock and move forward

**Comment by mcleo-d** [comment]
**Do not pick**. This epic is being groomed down to it's individual component parts. 

- [x] Discussions epic found here ▶️ #22
- [ ] Teams epic found here ▶️ ...
- [ ] Issues epic found here ▶️ ...

**Comment by maoo** [comment]
I believe that this issue have been delivered, given that we have all epics consolidated on https://github.com/finos/open-developer-platform/issues and a migration process running.

For more info on GitHub best practices, please follow https://github.com/finos/open-developer-platform/issues/38
