### ISSUE TITLE
Using Github Discussions in place of Google Groups

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#22]
As part of our long term strategic intent to consolidate as much of our collaboration infrastructure on Github, this epic is about doing a pilot using github discussions in place of google groups, probably in 1-2 projects to start.

One consideration that has been brought up is whether Github Discussions provides sufficient (or any) of the monitoring, data collection, and surveillance, required by the banks which remains a reason we still are on Google Groups (despite the fact that some banks can't use Google applications like Google Groups).

## Key requirements:
- Discussions can be followed via email (email notifications)
- Discussions can be joined via email (ie via reply-to email from notifications)
- Users can be invited to or banned by discussions, from discussion maintainers
- FINOS Org admins can manage discussion maintainers for each discussion
- Discussions can link to other GitHub items: issues, PRs, projects, code, repositories, user (mentions), 

## Stories:
- [ ] Arrange a date when the GitHub team can join an ODP working group call 
- [ ] Place the GitHub discussion and initial grooming session on the ODP agenda
- [ ] Discuss the initial items ODP needs to investigate, solve and deliver to move forward
- [ ] Add the initial items to the ODP GitHub issues and delegate to ODP team members to solve
- [ ] Add updates to future ODP agenda to help unblock and move forward

We're looking for a volunteer who would like to setup a simple dry run; it can be hosted on anyone's GitHub account/org.

**Comment by ColinEberhardt** [comment]
Yes, yes, and yes - please do this :-D

Although, I understand that this is a challenge for the "monitoring, data collection, and surveillance" requirements, however, Google Groups are a significant source of friction for external collaborators and contributors.

**Comment by maoo** [comment]
I wrote some docs about it, see https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-Conversations . There's not much to say TBH, GitHub docs are quite complete.

I think it would be good to try it out a bit, I've started some private/public discussions in https://github.com/orgs/finos/teams/fdx-odp/discussions 

@ColinEberhardt - feel free to review the docs and share your thoughts, TY!

**Comment by jbjonesjr** [comment]
Another suggestion: https://news.ycombinator.com/item?id=22388639

**Comment by mcleo-d** [comment]
@jbjonesjr and @maoo

I'd like to suggest the following two FINOS repos (projects) for the GitHub Discussions beta ...

1. **Open Developer Platform** - https://github.com/finos/open-developer-platform
2. **Cloud Service Certification** - https://github.com/finos/cloud-service-certification

The justification for the suggestions are ...

* @mcleo-d is helping run both projects and can bring a level of consistency to the GitHub beta.
* ODP includes members of the GitHub teams who can help oversee the beta.
* Both projects are accelerating due to working group activities, GitHub issues and project kanbans. 
* Both projects have a wide cross section of different participants, so we can measure how the discussions beta hits different parts of the FINOS community.

Please let me know your thoughts below.

James.

**Comment by mcleo-d** [comment]
I've assigned to @jbjonesjr to add FINOS projects to the GitHub alpha and have updated the status to **In Progress**.

**Comment by mcleo-d** [comment]
@mcleo-d has been introduced to a GitHub project manager to discuss FINOS taking part in the GitHub Discussions Beta trial against selected repos. 

The initial conversation will happen on 30th March 2020. Thank you @jbjonesjr for organising the introductions! 💪

**Comment by mcleo-d** [comment]
Welcome to the conversation @becca 😀 

Thank you for enabling GitHub Discussions on https://github.com/finos/open-developer-platform/ and https://github.com/finos/cloud-service-certification

It'll be great to invite you to a future ODP meeting to talk through the functionality.

James.

**Comment by maoo** [comment]
Here's a good example of public discussion on GitHub - https://github.com/finos/open-developer-platform/discussions/163

**Comment by maoo** [comment]
Moved to https://github.com/finos/open-developer-platform/discussions/194 , closing issue
