### ISSUE TITLE
Add WhiteSource documentation on vulnerability details

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#24]
## Acceptance Criteria
- [ ] As project visitor, I want to read documentation on WhiteSource vulnerability details

## Tasks
- [x] Review https://whitesource.atlassian.net/wiki/spaces/WD/pages/697696422/WhiteSource+for+GitHub.com
- [x] Report/link relevant info on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530440/WhiteSource
- [ ] Discuss and socialise changes via ODP meeting

**Comment by maoo** [comment]
Added link to WhiteSource docs, see https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1129283585/WhiteSource+for+GitHub.com . Link is https://whitesource.atlassian.net/wiki/spaces/WD/pages/697696422/WhiteSource+for+GitHub.com#WhiteSourceforGitHub.com-ViewingDetailsofanIssue

Will discuss this during next ODP meeting , see https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1428750363/2020-03-11+ODP+WG+Meeting+notes
