### ISSUE TITLE
Quality checks are performed automatically and continuously upon any new incoming code

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#28]
### Acceptance Criteria
- [ ] As a project visitor, I want to see in the GitHub README the status of quality continuous checks
- [ ] As a FINOS Project Team member, I want to rely on automatic quality checks provided/suggested by FINOS
- [ ] As a FINOS Project Team member, I want to be able to configure quality checks using GitHub files (GitOps)

### Tasks
- [ ] Ensure all GitHub repositories have a summary, automatically and continuously - #31
- [ ] Ensure all GitHub repositories have a FINOS Project Lifecycle badge in README.md, automatically and continuously - #16

**Comment by mcleo-d** [comment]
@maoo - I have assigned the atomic label as this story forms part of the following ODP epic 👍 

https://github.com/finos/open-developer-platform/issues/34

**Comment by maoo** [comment]
Given the introduction of LFX in our infrastructure, we are going to rely on those collaboration tools.

Closing issue and marking it with LFX label.
