### ISSUE TITLE
New FINOS projects enrolment using FINOS Project Blueprint

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#29]
Depends on https://github.com/finos/open-developer-platform/issues/37

## Acceptance criteria
- [x] As a FINOS Contributor, I want to be able to create and setup a GitHub repository with all default FINOS contents/settings
- [x] As a FINOS Contributor, I want to be able to align an existing project with all default FINOS contents/settings

## Tasks
- [x] Document process to create a new FINOS project using https://github.com/finos/project-blueprint
- [x] Document process to align an existing FINOS project a new project using https://github.com/finos/project-blueprint

**Comment by maoo** [comment]
Done! Delivered on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting+and+GitOps#CodeHosting(andGitOps)-FINOSProjectblueprint
