### ISSUE TITLE
Implement ongoing license validation of all hosted repositories

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#30]
### Description of Problem:
Rather than relying solely on contribution-time license validation, the Foundation needs to ensure license compliance for all hosted repositories on an ongoing basis.

### Potential Solutions:
A spike using https://github.com/fossas/fossa-cli have shared on https://gist.github.com/maoo/40a4f7a9df8315290a1b0c347dd018da

Below the description of a GitHub Action that could deliver a continuous scanning across any GitHub repo (whose build command is supported by fossa.io

#### Proposal
> Build a standard GitHub action that reacts on commits and Pull Requests (PRs) on a given GitHub repository, called FOSSA GitHub Action.

Every time that a commit is pushed or a PR is merged, the FOSSA GitHub Action is triggered, the action

- [ ] Reads a .fossa-licenses.yaml file, containing
-- A list of SPDX IDs called "compatibleLicenses"
-- A list of SPDX IDs called "incompatibleLicenses"
-- A list of strings called "whitelistedLibraries"
-- ... (more will come after the MVP)
- [ ] Reads the FOSSA_API_KEY (encrypted) environment variable, containing the key of FINOS account
- Invokes "fossa init" and "fossa report licenses --json", generating a JSON payload with all library and license definitions
- [ ] Parses the generated JSON (on step 5) and builds a report with
-- List of libraries with compatible licenses (and the compatible license that applies)
-- List of libraries with incompatible licenses
-- List of libraries with unknown licenses 
- [ ] Formats the report in Markdown and post on a new github issue. If the action was triggered by a PR, the check will succeed or fail based on the amount of incompatible /unknown licenses found

**Comment by mcleo-d** [comment]
Hi @maoo

I've tagged @alphax777 to help groom and prioritise this issue as part of ODP. @alphax777 feel free to tag other FOSSA team members who could potentially help us resolve.

Many thanks 🤜💥🚀

James.

**Comment by maoo** [comment]
Tracking this activity internally; we can close this issue.
