### ISSUE TITLE
Ensure all GitHub repositories comply with project-blueprint repo template

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#31]
### Description of Problem:
All FINOS repositories should include a one line summary as supported by GitHub, to better support navigation and consumption of the project portfolio; along with other basic GitHub repository settings, each repository should include:
- a `README.md` file
- a `whitesource.config` and `.whitesource` file
- a `.github` folder with sub-files in it
- .... TBD (see https://github.com/finos/project-blueprint )

### Stories:
- [x] https://github.com/finos/metadata-tool/pull/53 Implement check command in metadata-tool
- [x] Present to ODP
- [x] Finalise, test and document [GitHub Action that creates GitHub Issues on repositories](https://github.com/finos/open-developer-platform/blob/master/.github/workflows/project-blueprint.yml)

**Comment by mcleo-d** [comment]
@maoo - Please label **ready for dev** if this story can be taken forward.

**Comment by maoo** [comment]
TY, good to know! I think it still needs a clear set of requirements and a decomposition... it's unclear yet what the outcome of the initiative is (ie, does the bot create PRs? Will they be labeled somehow? What's the PR content?).

Happy to decompose it a bit more, but probably not the highest priority. For sure, it's linked to https://github.com/finos/open-developer-platform/issues/11 , so if we make progress on similar activities, this may become much easier to solve.

With all this said, would you still label it ready for dev? Or maybe use another label?

**Comment by maoo** [comment]
Great progresses on this issue, see https://github.com/finos/metadata-tool/pull/53 .

Next items:
- [ ] Announce it to ODP meeting and socialize it
- [ ] Implement a GitHub Action (in the ODP repo) that creates/updates/reopens an issue on each repo titled "FINOS Project Blueprint checks", adding the message extracted by the report as description
- [ ] Run the action on a scheduled bases - but avoid issue duplicates

**Comment by maoo** [comment]
GitHub Action is ready! https://github.com/finos/open-developer-platform/commit/edf08d9a567f4d0644ec2f7e4508c9e4de3f46da It still doesn't create issues.

**NOTE!** the API call that creates the issues is still commented out, until we communicate it to project leads and wider community.

**Comment by maoo** [comment]
The PR is in review, but we can already use metadata-tool to build the full report in CSV format. Next suggested steps are - while working on merging the PR:
- [ ] Finalise, test and document [GitHub Action that creates GitHub Issues on repositories](https://github.com/finos/open-developer-platform/blob/master/.github/workflows/project-blueprint.yml) (create issue)
- [ ] Announce and socialise the GitHub Action with ODP and at least 2 other teams (create issue)
- [ ] Enable the action (create issue)
- [ ] Define reporting and notifications, see https://github.com/finos/open-developer-platform/issues/33 and https://github.com/finos/open-developer-platform/issues/107

**Comment by maoo** [comment]
@mcleo-d - docs are in place - http://odp.finos.org/docs/development-infrastructure/code-validation/intro#project-compliance-scan

I think we're ready to send a heads up to the wider community, so we can enable the GitHub action and submit the GitHub issues to repositories!

**Comment by mcleo-d** [comment]
Creation of action to scan through FINOS repositories and raise issues is done. The following items are now raised and need to be prioritised for review.

* **Announce and Socialise** : #114 
* **Reporting and Notifications** : #33

**Comment by mcleo-d** [comment]
Code review of finos/metadata-tool#53 done with @maoo 👍
