### ISSUE TITLE
FINOS project leads can ensure quality, security and compliance of FINOS hosted code

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#34]
### Description
An epic to ensure quality, security and compliance is applied to all FINOS projects.

### Stories:
- [ ] #28 License, security and quality checks are performed automatically upon any new incoming code (initial, commits, PRs)
- [ ] #29 New Projects and repositories are automatically enrolled in this configuration based on https://github.com/finos/project-blueprint/
- [ ] #32 Project leads are provided a way to override specific packages to allow build / merge to succeed
- [ ] #33 PMCs / secretary@ is notified about project specific overrides

**Comment by maoo** [comment]
This seems to be duplicative of https://github.com/finos/open-developer-platform/issues/28 and https://github.com/finos/open-developer-platform/issues/30 . I've moved the mentioned items to the linked issues, so that nothing got lost.
