### ISSUE TITLE
WhiteSource rollout Pilot

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#35]
Depends on #27

### Description
List of trending projects for the rollout:
- [x] cla-bot
- [x] datahelix
- [x] openfin-react-hooks
- [x] plexus-interop
- [ ] finos-plexus.github.io
- [ ] perspective
- [ ] cloud-service-certification
- [ ] kdb
- [ ] greenkey-discovery-sdk
- [ ] greenkey-asrtoolkit

### Stories
- [ ] Create blogpost about WhiteSource rollout

### Task History
- https://finosfoundation.atlassian.net/browse/INT-744

**Comment by mcleo-d** [comment]
Hey @maoo - Are there representatives from each of the following teams who can integrate WhiteSource from the [FINOS Project Blueprint](https://github.com/finos/project-blueprint) whilst you oversee activity?

**Comment by maoo** [comment]
Hi @mcleo-d - the WhiteSource bot provides an automatic PR when enabled; I'd follow WhiteSource suggestion and start with that, then wait for the teams to go through the issues being spotted and update the configuration accordingly.

We used this approach on https://github.com/finos/datahelix and I think it worked quite well.

One key element IMO is to reach out to the teams in advance and notify them that we are going to enable the WhiteSource scanning - which by default will open issues on GitHub - unless they prefer a different way of proceeding.

WDYT?

**Comment by mcleo-d** [comment]
> The WhiteSource bot provides an automatic PR when enabled; I'd follow WhiteSource suggestion and start with that, then wait for the teams to go through the issues being spotted and update the configuration accordingly, following our guidance/support.

Sounds like a relatively straight forward PR, which in my opinion is awesome! 👍 

> One key element IMO is to reach out to the teams in advance and notify them that we are going to enable the WhiteSource scanning - which by default will open issues on GitHub - unless they prefer a different way of proceeding.

Informing teams in advance is very wise, as experience shows, many relevant and irrelevant issues can appear on project issue boards. It's good to bring the team along with us, even with a quick notification.

**Comment by maoo** [comment]
Removing the following from description:
- [ ] finos-plexus.github.io
- [ ] perspective
- [ ] cloud-service-certification
- [ ] kdb
- [ ] greenkey-discovery-sdk
- [ ] greenkey-asrtoolkit

**Comment by mcleo-d** [comment]
Have moved **Create blogpost about WhiteSource rollout** to #82

**Comment by mcleo-d** [comment]
The following epic has been created for Hadouken related projects - #83
