### ISSUE TITLE
Improve WhiteSource security scanning at FINOS

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#36]
## Description
The following stories should be documented using markdown so they can be integrated into the Open Developer Platform wiki once available from epic #12  

## Stories
- [ ] #13 Provide an overview of ODP to WhiteSource so they understand the FINOS objectives of integrating WhiteSource into GitHub 
- [ ] Build a GitHub Action that runs the WhiteSource Unified Agent
- [ ] Provide a way for the bot to be re-summoned via comments on issues
- [ ] Make WhiteSource Bot configuration PR configurable (FINOS default configuration can be found at https://github.com/finos/project-blueprint)
- [ ] WhiteSource bot `excludes` should be configurable at bot (not scanning) level, ie in the `.whitesource` file
- [ ] Investigate, test and document WhiteSource PR automatic fix - https://www.whitesourcesoftware.com/whitesource-remediate/ (enabled by default for github.com integration)
- [] Document support from FINOS and WhiteSource, when related to security issues, scanning configuration and other related issues (FINOS liaises between community and WhiteSource, by opening tickets via support@whitesourcesoftware.com , /CC WS account manager for FINOS)

**Comment by mcleo-d** [comment]
Created #24 as an individual story to deliver independently.

- #24 Add documentation on vulnerability details: which info is reported, how does CVSS 2 Score work (min and max)

**Comment by mcleo-d** [comment]
Added #13 **Provide an overview of ODP to WhiteSource so they understand the FINOS objectives of integrating WhiteSource into GitHub** to the epic.

**Comment by maoo** [comment]
Closing this for now, we will react on possible WS integration improvements and take it from there.
