### ISSUE TITLE
Create an ODP microsite and wiki using the Docusaurus JavaScript framework

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#37]
Relates to https://github.com/finos/open-developer-platform/issues/29

## Summary
As Docusaurus has become the FINOS reference solution for delivering project microsites, it would be great to have a template structure in https://github.com/finos/open-developer-platform to encourage ODP documentation collaboration.

## Acceptance Criteria
- [x] as ODP visitor, I want to access wiki contents via odp.finos.org
- [x] as ODP visitor, I want to propose wiki changes via PRs on https://github.com/finos/open-developer-platform

## Tasks
- [x] Build a white label microsite with Docusaurus (for FINOS ODP) on https://github.com/finos/open-developer-platform
- [x] Create inline edit links as part of white labeled Docusaurus build
- [ ] #56 Add ODP branding to ODP white label Docusaurus microsite
- [x] Setup ODP microsite DNS and make ODP Docusaurus live #79

**Comment by mcleo-d** [comment]
Transferred **implementing meeting attendance via markdown files on GitHub** to #78

**Comment by mcleo-d** [comment]
Transferred **Setup ODP microsite DNS and make ODP Docusaurus live** to #79

**Comment by mcleo-d** [comment]
Transferred **Migrate ODP content from FDX section of FINOS confluence wiki to ODP Docusaurus microsite** to #80

**Comment by mcleo-d** [comment]
Tagging @brntbeer as work sponsor

**Comment by maoo** [comment]
All done except branding and announcement. I'll close this one and mark the branding issue as `epic`
