### ISSUE TITLE
FINOS Tailored Git and GitHub Training

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#38]
### Description of Problem:
Developing and distributing FINOS specific/tuned Git/Github101 training has come up a few times. Programs that have suggested this be done include FDC3, FO, and DT (specifically the Kdb WG). 

This epic is to capture those requirements so the ODP WG, FDX program and FINOS community can assess if Git/GitHub 101 training is something to take on, develop, distribute and deliver. 

There is a draft/scratch pad, which @mcleo-d, @jbjonesjr and the ODP team has access to in FINOS.

As some have pointed out, there is a lot of good Git/Github training already, but the feedback we've received is that it would be good to have training material that is tuned to FINOS, FINOS processes, and FINOS tooling that includes examples and screenshots of FINOS tools such as Travis CI and CLA Bot.

### Potential Topics:
- Source Control 101
- How Git is different from SVN, CVS, and other "traditional" tools
- Basic concepts: Commits, Forks, Pull Requests, Etc.
- Using Github interactively (and comparison with doing stuff at command prompt)
- Github 101
- Markdown 101
- FINOS CLAs, the CLA Bot, and the FINOS Metadata model
- The FINOS project blueprint
- Using Github projects/using github for a kanban board
- Using Github as a wiki
- Github Pages 101, Docusaurus, and the FINOS microsite template

### Examples of Git/Github training we might be able to leverage
- [Harvard CS50 Git/Github training](https://www.youtube.com/watch?v=MJUJ4wbFm_A)
- [Git SCM](https://git-scm.com/)

## Stories
- [ ] Refine list of training topics and set ToC on github.com/finos/open-developer-platform GitHub Pages
- [ ] Organize quarterly training sessions via ODP meetings
- [ ] Run first training session
- [ ] Update ODP GitHub pages with training content (after first training session)

More history on https://finosfoundation.atlassian.net/browse/ODP-103

**Comment by mcleo-d** [comment]
Also relates to https://github.com/finos/finos-pmcs/issues/9

**Comment by mcleo-d** [comment]
@tschady previously noted - https://guides.github.com/ should be all anyone needs for git and github.

**Comment by maoo** [comment]
Created specific epic for GitLab - https://github.com/finos/open-developer-platform/issues/40

**Comment by maoo** [comment]
Closing this issue for now, as there haven't been updates on it since a long time.

There is a good amount of documentation that can be found on https://community.finos.org
