### ISSUE TITLE
Create the ability to manage meeting minutes on GitHub that includes Bitergia reporting

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#39]
### Description of Problem
So far, the only tool used in FINOS to edit and store meeting minutes is Atlassian Confluence;  this is - for example - the list of meetings held by the FDC3 Appd Working Group - https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/130711602/AppD+Meeting+Minutes

In order to workaround the known Atlassian Confluence accessibility issues (firewalled by most FINOS members), GitHub Wiki can be tested in order to provide an alternative platform for editing and storing meeting minutes.

### Tasks include, but are not limited to:

- [ ] Implement and test Bitergia meetings crawler to also scan GitHub Wiki pages (MarkDown format, see https://github.com/yogthos/markdown-clj#table)
- [ ] Define meeting minute page template (and guidelines, preferably a button to create a new page from template) to easily create meeting minutes pages
- [ ] Create (in an automated fashion) meeting minute page templates for each project or working group, including the roster, in order to simplify the minutes editing during calls (instead of typing the name of attendees, check/uncheck a box close to the names listed in a predefined table, then optionally add new attendees down below)
- [ ] Test GitHub Wiki platform to take notes of the next ODP WG meeting
- [ ] Communicate and socialise with FINOS Staff (first) and Community (later)

### Technical Dependencies:
This project relies on the delivery of story #37 prior to development start.

More history on https://finosfoundation.atlassian.net/browse/ODP-90

**Comment by mcleo-d** [comment]
Previous feedback to this epic includes the following idea for simplifying reporting made by @brooklynrob due to the complexities of parsing table data in documents.

>We look for another way to track attendance. I’d welcome any and all ideas here. Maybe attendees SMS their name and email somewhere. An obvious idea would be to use WebEx itself, but the problem there is call-in users. More generally I’d like to see us avoid anything that requires some manual intervention post-meeting by either a member of the community or FINOS staff.

**Comment by maoo** [comment]
Closing this as dup of https://github.com/finos/open-developer-platform/issues/78
