### ISSUE TITLE
FINOS projects can be hosted on GitLab

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#40]
## Stories
- [ ] #15 - CLA bot on GitLab
- [ ] Index GitLab.com projects activity on metrics.finos.org
- [ ] Publish GitLab project links on finos.github.io project catalogue
- [ ] GitLab Trainings for FINOS (similar to https://github.com/finos/open-developer-platform/issues/38)

**Comment by maoo** [comment]
Dup of https://github.com/finos/open-developer-platform/issues/72 , closing
