### ISSUE TITLE
FINOS voting best practices and automation

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#46]
## Description :
Document what are the best practices for managing votes by a FINOS activity group

## Stories
- [ ] List links to public voting activities that have happened in FINOS so far (ie VOICE and FDC3 programs)
- [x] Define a proposed voting mechanism based on GitHub.com platform (ie GitHub Issue templates + thumbs up/down emoji + automation, if needed)
- [x] Present and discuss the proposal during ODP meeting
- [x] Document
- [ ] Adopt voting practice at least once within the FDX program
- [ ] Socialise with community@finos.org and pan-pmc group

**Comment by mcleo-d** [comment]
@maoo - Can you add some more detail to this epic just in case a member of the community takes interest and wants to fill gaps or run a spike?

**Comment by maoo** [comment]
@mcleo-d - here's a proposal for ODP - https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting+and+GitOps#CodeHosting(andGitOps)-Voting

I've scheduled a quick test during next ODP call, let's see how it works!

**Comment by maoo** [comment]
This feature is done and ready for rollout.

**Comment by maoo** [comment]
Skipping the following items for the rollout phase:
- [ ] Adopt voting practice at least once within the FDX program
- [ ] Socialise with community@finos.org and pan-pmc group
- [ ] List links to public voting activities that have happened in FINOS so far (ie VOICE and FDC3 programs)
