### ISSUE TITLE
Add "Projects with open vulnerabilities" to monthly FINOS PMC report

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#52]
### Description :
Add "Projects with open vulnerabilities" to monthly PMC report

### Required: 
- [ ] List any projects within a program that have an identified vulnerability

### Better still: 
List projects based on their lifecycle and consistent with the lifecycle criteria:

- [ ] Show incubating projects with critical or high vulnerabilities (but an incubating project with, say, only medium vulnerabilities would not be listed)
- [ ] Show active projects with any vulnerabilities

### Task History
Originating from https://finosfoundation.atlassian.net/browse/INT-733

**Comment by maoo** [comment]
Closing this one, as the PMC report have been dismissed.
