### ISSUE TITLE
ODP website styling

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#56]
### Add ODP branding to ODP white label Docusaurus microsite

The Open Developer Platform Docusaurus microsite is commited to the [odp-issues-37-docusaurus-white-label-wiki](https://github.com/finos/open-developer-platform/tree/odp-issues-37-docusaurus-white-label-wiki) branch in GitHub whilst in development by the ODP project team.

- Fork the Open Developer Platform repository to your GitHub profile
- Git clone your forked repository to your local machine
- Git fetch all branches from your forked GitHub repo to your local machine
- Git checkout odp-issues-37-docusaurus-white-label-wiki locally and add changes to this feature branch
- Push odp-issues-37-docusaurus-white-label-wiki to odp-issues-37-docusaurus-white-label-wiki on your forked repo
- Raise a PR to odp-issues-37-docusaurus-white-label-wiki in the open-developer-platform project when changes ready to be merged upstream

### Tasks to include

- [x] Add ODP logo / icons to ODP Docusaurus microsite
  - [x] Header
  - [x] Main Panel 
  - [x] Footer
- [x] Add ODP favicon to ODP Docusaurus microsite
- [x] Swap grey SVG boxes to generic checkmark SVGs 
- [x] Add ODP specific CSS to Docusaurus microsite

**Comment by mcleo-d** [comment]
Hi @maoo - Can you add @grizzwolf to the FINOS organisation so I can assign this story?

Thanks 👍

**Comment by mcleo-d** [comment]
@grizzwolf - This story is now **Ready for Development**. 

Let me know if you need any help or support 👍 

James.

**Comment by grizzwolf** [comment]
Was able to get the background images to show, working on their placement. Changed the featured images to best sizing - but now have to increase size of other images (they were / are all tied together since each index id was named Features - added Members and Projects to isolate the CSS. Still clean up to do on sizing / coloring on home - but basic blocks are there.

![screencapture-localhost-3000-index-staging-2020-05-18-11_51_46](https://user-images.githubusercontent.com/873426/82233588-40882200-98fe-11ea-9d6c-87ac3e59c599.png)

![screencapture-localhost-3000-index-staging-2020-05-18-11_51_32](https://user-images.githubusercontent.com/873426/82233603-43831280-98fe-11ea-9959-ec53469d7f33.png)

**Comment by maoo** [comment]
@grizzwolf - love it! We should remove the titles below the members and projects items. I'll wait for your PR before making the change. Feel free to submit the changes. TY!

**Comment by grizzwolf** [comment]
Made updates and was able to get coloring and sizing better. Let me know if this seems to work and I can push.

![screencapture-localhost-3000-index-staging-2020-05-18-12_53_16](https://user-images.githubusercontent.com/873426/82239625-11c27980-9907-11ea-9edd-fa6fa4ea0bc6.png)

![screencapture-localhost-3000-index-staging-2020-05-18-12_55_46](https://user-images.githubusercontent.com/873426/82239621-10914c80-9907-11ea-852a-a7279207fcac.png)

![screencapture-localhost-3000-index-staging-2020-05-18-12_56_11](https://user-images.githubusercontent.com/873426/82239618-0ff8b600-9907-11ea-8d61-8106f87ce427.png)
![screencapture-localhost-3000-index-staging-2020-05-18-12_56_24](https://user-images.githubusercontent.com/873426/82239609-0c652f00-9907-11ea-95ca-2fe786ddd423.png)

**Comment by maoo** [comment]
@grizzwolf - fantastic job! Send the PR and I'll merge it right away. Thank you!

**Comment by mcleo-d** [comment]
@grizzwolf and @maoo - The new ODP website is fantastic. Please let me know if I can help debug HTML and CSS. I'm more than happy to get involved if needed 👏 👏  💯 💯 💯

**Comment by maoo** [comment]
https://odp.finos.org/index-staging is updated. @grizzwolf you did a superb job here, we can close the issue.

@mcleo-d - thanks for the offering, would you be happy to help reviewing the message of the page? I've created https://github.com/finos/open-developer-platform/issues/135 , let's work there so we can plan ahead how we bring this wonderful website (a)live! 😄
