### ISSUE TITLE
Document FINOS membership on GitHub.com team management

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#71]
Following up from #21 , we need to deliver clear guidance to our community regarding the following the questions:
- [x] Who is authorized to be a FINOS GitHub Member?
- [x] What does FINOS GitHub membership entitle/grant?
- [x] How to request/get FINOS GitHub membership?
- [x] What FINOS activities require FINOS GitHub membership? And what not?
- [x] How are FINOS GitHub teams structured? How to use them (ie mentions) ?
- [x] Who can maintain GitHub teams for FINOS Projects?
- [x] What is a team member entitled to within github.com/finos ?
- [x] Who can become a Project team member and how?
- [x] What is a Project Lead entitled to within github.com/finos ?

The Wiki page where I'd expect these contents to be is https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting , however, there is a draft page started on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/1165361155/DRAFT+Collaboration+on+GitHub ; also, the attached PDF (
[FINOS.on.GitHub.-.settings.and.processes.pdf](https://github.com/finos/open-developer-platform/files/4343909/FINOS.on.GitHub.-.settings.and.processes.pdf)
) contains documentation written in the past by FINOS and GitHub to consolidate different program-specific GitHub orgs into github.com/finos .

Below some exissting documentation that describes GitHub's permissioning model:
- [Access Permissions on GitHub](https://help.github.com/en/github/getting-started-with-github/access-permissions-on-github#organization-accounts)
- [GitHub Teams](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams)

Related issues:
- https://github.com/finos/open-developer-platform/issues/10 - Meta conversation around GitHub.com setup for FINOS
- https://github.com/finos/open-developer-platform/issues/21 - Testing best practices on GitHub.com for FINOS
- https://github.com/finos/open-developer-platform/issues/70 - Tagging users outside of GitHub org

**Comment by issc29** [comment]
@maoo FYI here is some documentation that describes GitHub's permissioning model:
* [Access Permissions on GitHub](https://help.github.com/en/github/getting-started-with-github/access-permissions-on-github#organization-accounts)
* [GitHub Teams](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams)

**Comment by maoo** [comment]
> How to request/get FINOS GitHub membership?

There is `Invite me` feature for GitHub orgs; it is possible to create an Issue Template, to guide users in the process to applying for GitHub FINOS membership

**Comment by maoo** [comment]
Content on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting updated. Needs review and some fixes on styling, but content should be mostly there (I merged all sources mentioned in the issue description).

@mcleo-d , can you please review and LMK WYT?
