### ISSUE TITLE
GitLab.com/finosfoundation config/settings improvements

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#72]
gitlab.com/finosfoundation configuration and settings could be improved, based on the experience managing GitHub orgs.

- [ ] Logo and description
- [ ] Add FINOS staff as members
- [ ] #15 - CLA bot on GitLab
- [ ] Update Wiki documentation on how to request access
- [ ]  Add repositories to FINOS Metadata and link them on finos.github.io
- [ ] Index GitLab.com projects activity on metrics.finos.org
- [ ] GitLab Trainings for FINOS (similar to #38)
- [ ] ... more to be added

**Comment by maoo** [comment]
Tracking this internally.
