### ISSUE TITLE
Automated license scanning for FINOS projects

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#76]
At FINOS we're facing 2 major issues with license scanning:

1. Using the Fossa dashboard and policies, we get lots of false positives due to common dually licensed libraries (ie Jersey); given the amount of projects hosted in FINOS, and the amount of technologies involved, it's not possible for FINOS team to curate the white/blacklisting of singular libraries, so we'd have to rely on project teams to manage them.

2. As we continue adopting GitOps as collaboration model, we'd need to provide project teams the ability to curate white/blacklisting via Git operations, ie editing the list in the .fossa.yml file

Please note that challenges have been experienced, in different ways, with all licensing scanning products we tested. And that's the reason that led us to start experimenting with Fossa CLI, see #30 .

Right now we're trying to bundle the Fossa CLI spike on a GitHub Action, so that it can continuously run on every commit; when that part is figured, we'd need to build some logic to:
- [ ] Extract/massage the JSON output of the Fossa CLI (the spike currently uses JQ)
- [ ] Load the .fossa.yml configuration from the project
- [ ] Load the .fossa.yml configuration at org level, if any and merge it with the project ones
- [ ] Cross reference white/blacklists with Fossa CLI output
- [ ] Format output, post a GitHub comment, fail PR validation

Wondering if there's anything in next FOSSA releases that can help us with some of our challenges

/CC @alphax777

**Comment by mcleo-d** [comment]
@maoo and @alphax777 - I've tagged the people related to this issue in this comment so we can continue conversations here prior to ODP working group meetings.

Welcome to ODP issue #76 🤜💥🚀

James.

**Comment by maoo** [comment]
This is duplicative of #30 - closing.
