### ISSUE TITLE
Implement meeting minutes (and attendance tracking) on GitHub

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#78]
### Description
Right now meeting minutes are managed in Atlassian Confluence; meeting attendance is tracked using a script (in [metadata-tool](github.com/finos/metadata-tool) that crawls HTML payloads and parses table structures, which is quite delicate and subject to all sorts of maintenance challenges.

Atlassian Cloud is also hard to access behind financial institutions firewalls, therefore not everyone can manage meeting minutes.

Given that GitHub Issues is often used for collaboration in our community, it can be also used to describe meeting minutes, while issue assignees specify the meeting participants; when the issue is labeled, a GitHub action kicks in, interacts with metadata-tool, resolves identities, generates CSV (deltas) and submits changes to the remote Git repositories that host this data.

### Success Criteria
- [x] as ODP Team member, I want to manage meeting agenda and rosters on https://github.com/finos/open-developer-platform/issues

### Tasks to Complete

- [x] Groom this story with potential implementation solutions before moving into development
- [x] Spike potential solution from markdown in GitHub through to Bitergia reporting
- [x] Implement and test meeting attendance via GitHub Issues
- [x] Run ODP meeting agenda and roster via GitHub Issues (scheduled for March 25 2020) and demo
- [x] Publish documentation

**Comment by maoo** [comment]
I've come up with a GitHub Action that updates meeting attendance CSV files remotely.

Code is on https://github.com/finos/open-developer-platform/blob/master/.github/workflows/meetings.yml (also check the (scripts)[scripts] folder).

Docs can be found on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting+and+GitOps#CodeHosting(andGitOps)-MeetingMinutes

I'll demo it during next ODP meeting, see #85 ; if successful:
- [ ] ODP will keep on running meeting attendance this way, updating docs and links accordingly
- [ ] Follow up with Bitergia Support to add finos-github-meetings.csv into dashboards
- [ ] Socialise with wider FINOS community

**Comment by jbjonesjr** [comment]
This is so cool

**Comment by maoo** [comment]
@jbjonesjr - if you love GitHub Actions (as I do), checkout #31 , as it shares the same architecture of this action, and provides a powerful feature.

**Comment by maoo** [comment]
All done, marking issue as closed and ready for the rollout!
