### ISSUE TITLE
Setup ODP microsite DNS and make ODP Docusaurus live

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#79]
### Description

When the ODP Docusaurus microsite is ready to go live implement the steps needed for the microsite to be visible and browsable.

### Tasks to Complete

- [ ] Implement GitHub actions for building the ODP microsite as per FINOS Project Blueprint #19
- [ ] Create microsite DNS entry for ODP (odp.finos.org)
- [ ] Make ODP microsite live for external views on https://odp.finos.org
- [ ] Test https://odp.finos.org to make sure all relative paths are working and content is available
