### ISSUE TITLE
Create blogpost about WhiteSource rollout

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#82]
### Description
Create blogpost about WhiteSource rollout

### Tasks
- [ ] Work with FINOS marketing team to define the scope of the blog post
- [ ] Create blog post and review with FINOS marketing team
- [ ] Publish blog post on FINOS website with the FINOS marketing team

**Comment by maoo** [comment]
Rollout has passed already, so closing issue. We may want to create new posts in the future, when adding new features.
