### ISSUE TITLE
Enable WhiteSource Integration on Hadouken related projects 

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#83]
### Description
Integrate WhiteSource vulnerability scanning on Hadouken following the announcement of WhiteSource being available for all FINOS projects. 

### Tasks and Activities

- [ ] Schedule integration of WhiteSouce with @chuckdoerr and Hadouken PMC.

- [ ] Integrate and test WhiteSouce integration with the following Hadouken projects ...
  - [ ] https://github.com/HadoukenIO/core
  - [ ] https://github.com/HadoukenIO/js-adapter
  - [ ] https://github.com/HadoukenIO/symphony-of
  - [ ] https://github.com/HadoukenIO/app-template
  - [ ] https://github.com/HadoukenIO/notifications-service
  - [ ] https://github.com/HadoukenIO/layouts-service
  - [ ] https://github.com/HadoukenIO/service-utils
  - [ ] https://github.com/HadoukenIO/zero-downtime-trading-web-ux
  - [ ] https://github.com/HadoukenIO/fdc3-service
  - [ ] https://github.com/HadoukenIO/layouts-tabstrip
  - [ ] https://github.com/HadoukenIO/fdc3-sender
  - [ ] https://github.com/HadoukenIO/service-tooling
  - [ ] https://github.com/HadoukenIO/python-adapter
  - [ ] https://github.com/HadoukenIO/dotnet-fdc3-client
  - [ ] https://github.com/HadoukenIO/service-config

**Comment by maoo** [comment]
We won't enable WhiteSource on Hadouken for now, closing issue.
