### ISSUE TITLE
25 March 2020 - ODP Meeting minutes

### ISSUE THREAD

**Issue by maoo** [finos/open-developer-platform#85]
## Date
Wednesday 25 March 2020 - 12pm EST

## Untracked attendees

* Alessandro Petroni - [Red Hat](https://www.redhat.com/)

## Agenda
- [x] Convene & roll call (5mins)
- [x] @maoo - Walkthrough of GitHub documentation on FINOS Wiki - #71 can be closed?  (5mins)
- [x] @maoo - Walkthrough of meeting minutes on GitHub Issues  - #78 can be closed? Docs available at https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting+and+GitOps (10mins)
- [x] @maoo - Voting best practices - #46 - can be tested during the call; docs available at https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting+and+GitOps#CodeHosting(andGitOps)-Voting (10mins)
- [x] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Done in the last 2 weeks activity and archival (10mins)
- [x] [ODP Kanban](https://github.com/orgs/finos/projects/8) - Discuss In Progress and Prioritized issues (10mins)
- [x] AOB, Q&A & Adjourn (5mins)

## Action Items
- [ ] Demo new GitHub features at OSR
- [ ] Add items into marketing activities
- [ ] new ODP "message": request particular prio for a use case, via @mcleo-d ; day by day, ODP works with vendors to deliver use cases and "keeps the pulse" of community needs

### WebEx info
- [WebEx Meeting URL](https://finos.webex.com/finos/j.php?MTID=me6cd7441ee4946d919175d20a0b267a4)
- Meeting Number: 661 146 297
- Call from USA: +1-415-655-0003
- Call from CANADA: +1-647-484-1596 
- Call from UK: +44-20319-88141
- Call from Spain: +34-93545-2895

**Comment by maoo** [comment]
Thanks everyone for attending the meeting. To close on the meeting attendance tracking, here's the content of the CSV generated by the meeting action (in our Gitlab.com repo account, where we store this data).

<img width="1292" alt="Screenshot 2020-03-25 at 20 00 25" src="https://user-images.githubusercontent.com/327285/77575189-78ad4e80-6ed3-11ea-93d1-a9a1185d932b.png">

Marking the issue as closed (no effect, other than removing it from the TODO board column)

**Comment by mcleo-d** [comment]
The following action items have been carried over to meeting #138 for future prioritisation and scheduling.

- Demo new GitHub features at OSR
- Add items into marketing activities
- new ODP "message": request particular prio for a use case, via @mcleo-d ; day by day, ODP works with vendors to deliver use cases and "keeps the pulse" of community needs
